Update random generators
google/graphicsfuzz pull request #1152
Opened 2021-07-30 14:29 UTC by AaronGhost

Update random generators to support long generation and bounded
integers.

2021-08-02 08:16 UTC, afd requested changes
Looks good! A few changes requested.

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/IRandom.java
> +
Get rid of this extra line.

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/IRandom.java
> +  default int nextInt(int origin, int bound) {
Please add a JavaDoc comment indicating the range of integer that could be returned - i.e., making it clear that bound should be larger than origin, and that an integer in the range [origin, origin + bound) is returned.

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/IRandom.java
> +    return (int) (nextLong(((long)bound - (long) origin)) + (long) origin);
Precede the return by an assertion that bound > origin?

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/SameValueRandom.java
>    }
Please get rid of this, and instead adapt each existing SameValueRandom constructor to take 0L for its third argument.

2021-08-02 08:16 UTC, afd commented on generator/src/test/java/com/graphicsfuzz/generator/semanticschanging/Expr2BinaryMutationFinderTest.java
> +        return IRandom.super.nextInt(origin, bound);
Presumably this is never called as the original test didn't depend on it. So I suggest replacing the body with:

```
throw new RuntimeException("This method was added to the IRandom interface after this test was written and thus should not be called; if it becomes required the IRandom implementation in the test should be revised.");
```

2021-08-02 08:16 UTC, afd commented on generator/src/test/java/com/graphicsfuzz/generator/semanticschanging/Expr2BinaryMutationFinderTest.java
> +      }
Same.

2021-08-02 08:16 UTC, afd commented on generator/src/test/java/com/graphicsfuzz/generator/semanticschanging/Expr2BinaryMutationFinderTest.java
> +
Hmm, I might be missing something but I'm having trouble understanding why this wasn't required before your changes but is now.

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/CannedRandom.java
> +   * @param intsAndBools Ordered sequence of integers, long and booleans
Change the name to `intsLongsAndBools`

2021-08-02 08:16 UTC, afd commented on common/src/main/java/com/graphicsfuzz/common/util/CannedRandom.java
>    public CannedRandom(Object... intsAndBools) {
Change the name of the parameter.

2021-08-05 11:32 UTC, AaronGhost commented
Done

2021-08-05 23:10 UTC, afd approved these changes
LGTM.

2021-09-14 07:46 UTC, merged