Add support for std140 qualifier
google/graphicsfuzz pull request #1153
Opened 2021-07-30 14:35 UTC by AaronGhost

Updates the AST builder and adds a class for the qualifier.

2021-08-02 07:39 UTC, afd requested changes
Minor change requested.

2021-08-02 07:39 UTC, afd commented on ast/src/main/java/com/graphicsfuzz/common/ast/type/Std140LayoutQualifier.java
> + * Copyright 2019 The GraphicsFuzz Project Authors
Please change copyright year to 2021.

2021-08-05 11:00 UTC, AaronGhost commented on ast/src/main/java/com/graphicsfuzz/common/ast/type/Std140LayoutQualifier.java
> + * Copyright 2019 The GraphicsFuzz Project Authors
Done

2021-08-05 14:07 UTC, afd approved these changes

2021-08-05 23:08 UTC, merged